spring.application.name=bulletinBoard

server.port=8000

server.servlet.context-path=/bulletin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.active=prod

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8